### PR TITLE
Create simpleAspects.json

### PR DESCRIPTION
**Pull request by Craig-Bogun**
This is a simple aspect creator based on this page https://wiki.rpg.net/index.php/Aspects_List

### CODE REVIEW

**Comment by hkokko** [comment]
Omg - this is fabulous

**Comment by JochenLinnemann** [comment]
Very cool!

Just to be sure: What about the source of this content (the linked website)? Can we use this content here? Do we need to add attribution? Is the source license compatible with "https://github.com/open-campaign-logger/generator-library/blob/developer/LICENSE"?

Sorry for all this hassle but we must be sure to not infringe rights.

**Comment by evesala** [comment]
IANAL, but looks like it's not an impossible fit, as long as the required attribution is added to the generator: 

Apache FAQ has this on the subject: 

> Unmodified media under the Creative Commons Attribution-Share Alike 2.5, Creative Commons Attribution-Share Alike 3.0 and Creative Commons Attribution-Share Alike 4.0 licenses may be included in Apache products, subject to the licenses attribution clauses which may require LICENSE/NOTICE/README changes. For any other type of CC-SA licensed work, please contact the Legal PMC.

https://www.apache.org/legal/resolved.html#cc-sa 

(Not exactly our case, but close enough I guess.)

**Comment by Craig-Bogun** [comment]
I can add the link into the json file just so people know where is coming from, I intend to add to the lists as I find new content, there is a lot out there.

**Comment by Craig-Bogun** [comment]
Source has been added.

**Comment by Craig-Bogun** [comment]
The whole website uses this https://creativecommons.org/licenses/by-sa/2.5/ as per the bottom of the page.  We are sweet.

**Comment by evesala** [comment]
This is a great and useful generator, thank you for this! 

I did not yet accept the pull request, as it seems that the license should be explicitly stated and linked to: 
https://creativecommons.org/licenses/by-sa/2.5/ 

Perhaps a new key _license_ (similar to the _sources_ that you already have) should be used for cases like this? I could add it to the template as well. 

I’m away for the weekend so cannot investigate further now - sorry about that! I’m not an expert on license issues, so this needs some studying. If for example @JochenLinnemann has the time, great, but otherwise I’ll have to return to this next week. Thanks again for making this and sorry for the hassle!

**Comment by Craig-Bogun** [comment]
Fair enough, I have created a new line called "licence" and made the value https://creativecommons.org/licenses/by-sa/2.5/  I think that should satisfy the requirements.

**Comment by evesala** [comment]
Excellent work, thank you! I'm not a lawyer, but to me it seemed that the license requirements have now been fulfilled. 

This is useful stuff, and I appreciate how you have utilized also already existing generators. I hope we hear more from you! 

I believe there are many who would be interested in a generator like this, so feel free to announce it in the Google+ group if you want to: 
https://plus.google.com/u/0/communities/109734413216289457602 

Thanks again!

**Pull request merged**
